openapi: '3.0.3'
info:
  title: Categories api
  description: API for categories
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /api/v1/categories:
    get:
      summary: Get all categories
      operationId: getCategories
      tags:
        - Categories
      responses:
        '200':
          description: A list of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Electronics
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: Internal server error